[package]
name = "cli-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
access_log_parser = "0.9.0"
chrono = "0.4.38"
http = "1.1.0"
nom = "7.1.3"

[build-dependencies]
copy_to_output = "2.2.0"
